version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket codepipeline-us-east-1-394925491571 --output-template-file HelloWorldSAMTemplate.yaml
artifacts:
  types: zip
  files:
    - HelloWorldSAMTemplate.yaml
